%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\davee\Desktop\Senior Year\Spring Semester\Computer Methods\MatLab\gyro-dataset\A-known-rotation.csv
%
% Auto-generated by MATLAB on 15-Apr-2024 20:52:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_s", "WX_dps", "WY_dps", "WZ_dps"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Aknownrotation = readtable("C:\Users\davee\Desktop\Senior Year\Spring Semester\Computer Methods\MatLab\gyro-dataset\A-known-rotation.csv", opts);


%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\davee\Desktop\Senior Year\Spring Semester\Computer Methods\MatLab\gyro-dataset\B-unknown-rotation.csv
%
% Auto-generated by MATLAB on 15-Apr-2024 20:54:51

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_s", "WX_dps", "WY_dps", "WZ_dps"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Bunknownrotation = readtable("C:\Users\davee\Desktop\Senior Year\Spring Semester\Computer Methods\MatLab\gyro-dataset\B-unknown-rotation.csv", opts);


%% Clear temporary variables
clear opts

%% Graphing procedures + Integral calculations
% Only considering WZ measurements since the gyro data for WX and WY
% is mostly noise and therefore isn't useful in movement calculation.

A_Known = table2array(Aknownrotation);
B_Unknown = table2array(Bunknownrotation);

A_First_tmin = 13.3408;
A_First_tmax = 24.8873;
B_First_tmin = 12.4436;
B_First_tmax = 23.8789;

A_Second_tmin = 39.2775;
A_Second_tmax = 51.8563;
B_Second_tmin = 36.6207;
B_Second_tmax = 49.2996;

A_First_diff = A_First_tmax-A_First_tmin;
A_Second_diff = A_Second_tmax-A_Second_tmin;
B_First_diff = B_First_tmax-B_First_tmin;
B_Second_diff = B_Second_tmax-A_Second_tmin;



for i = 1:tsize

end
First90_A = trapz(A_Known(:,1),A_Known(:,4));
Second90_A = trapz(A_Known(:,1),A_Known(:,4));
First90_B = trapz(B_Unknown(:,1),B_Unknown(:,4));
Second90_B = trapz(B_Unknown(:,1),B_Unknown(:,4));

figure
plot(A_Known(:,1),A_Known(:,4))
title('Data A(Known)');
xlabel('Time (s)');
ylabel('Angular Velocity (DPS)');
legend('Wz')


figure
plot(B_Unknown(:,1),B_Unknown(:,4))
title('Data B(Unknown)');
xlabel('Time (s)');
ylabel('Angular Velocity (DPS)');
legend('Wz')

